### ISSUE TITLE
[feature request] Integrate with ipywidgets

### ISSUE THREAD

**Issue by horaceg** [ipyflow/ipyflow#115]
I just discovered ipyflow, it's really cool !

I see a huge potential for an integration with [ipywidgets](https://ipywidgets.readthedocs.io/en/stable/). Indeed, if one could simply do:
```python
import ipywidgets as w
from magic import widget

slider = w.IntSlider()
a = 10

b = a + widget(slider, "value")
```

And then b would update when the widget value changes, it would be awesome !

**Comment by smacke** [comment]
Hi there! Thanks for the kind words. We actually already have some integration with ipywidgets, but I'll have to check to see if I can get it working using the above approach as well.

The way I usually do it is

```python
b = a + slider.value
```

and if that line is in another cell, it should auto-rerun when the slider changes (provided reactivity is enabled with `%flow mode reactive`). Of course you can also do

```python
b = a + slider.$value
```

and it will update even if reactivity is not enabled, as well as

```python
b = a + slider.$$value
```

and then stuff that depends on `b` will also get reactively executed.

I haven't documented this yet in the readme since I usually wait until new features are extensively dogfooded before doing so, but this one is probably ready for primetime.

In case you're interested, another one is alt mode execute in JupyterLab -- when reactivity is disabled, cmd+shift+enter / ctrl+shift+enter on windows will trigger a reactive execution -- this allows you to see what will get reactively executed thanks to the highlights, and you don't have to commit to it until later. Sorry for going off topic but I'm really excited about that one :)

**Comment by smacke** [comment]
This feature is not documented and fully integrated, so going to go ahead and close out this issue :)
