### ISSUE TITLE
run_line_magic with local scope

### ISSUE THREAD

**Issue by daviddavo** [ipyflow/ipyflow#129]
I have a magic function that needs the local scope, it can be replicated like this:

```python
from IPython.core.magic import register_line_magic, needs_local_scope

@register_line_magic
@needs_local_scope
def printvarplusone(line, local_ns):
    x = local_ns.get(line)
    print(x + 1)
```

But instead of getting a dict with all the values where I can get the desired variable's value, I obtain a dict with a DataflowTracer object

I'm no expert, but I think this fixme might be relevant
https://github.com/ipyflow/ipyflow/blob/f9e1b1c50100228de44613bd07b2755461919dfc/core/ipyflow/line_magics.py#L174-L176

**Comment by smacke** [comment]
Thanks for opening an issue on this! I just pushed a fix -- you should be able to pick it up with

```
pip install --upgrade ipyflow
```

The issue wasn't around rewriting the `__name__` attribute of the function, but around setting `_stack_depth` correctly for `InteractiveShell.run_line_magic` (so that it looks at the correct stack depth for things like the locals).

Note that code in line magics doesn't get instrumented or traced, so you've identified an example wherein ipyflow won't actually correctly detect the usage of `x`, unfortunately. There are reasons we won't to disable instrumentation for line magics but just wanted to make sure you were aware of this caveat :)
