### ISSUE TITLE
Feature request: automatic update of dependent cells

### ISSUE THREAD

**Issue by stefaneidelloth** [ipyflow/ipyflow#87]
Is there a way to automatically update the dependent cells?

I am looking for a behavior that is similar to the behavior of
reactive observablehq notebooks or akernel:

https://github.com/davidbrochart/akernel

Related:
* https://github.com/davidbrochart/akernel/issues/24
* https://discourse.jupyter.org/t/dag-based-notebooks/11173/4
* https://stackoverflow.com/questions/69539309/how-to-monitor-state-of-observales-in-reactive-calculations
* https://discourse.jupyter.org/t/how-to-get-output-model-for-a-given-cell-in-a-jupyterlab-extension/11342

**Comment by smacke** [comment]
Update -- now that this package has been renamed nbsafety -> ipyflow, the new command is

```
%flow mode reactive
```

and to go back to normal,

```
%flow mode normal
```

**Comment by smacke** [comment]
ipyflow has come a long way since this issue was originally opened, and now various entrypoints of reactivity are mostly documented in the readme. Another one is cmd+shift+enter (on mac) or ctrl+shift+enter (on other OSes) to trigger a reactive execution, even in normal mode (will have it readme-documented soon). Since the spirit of this issue has largely been addressed, I am going to go ahead and close it out.
